spring.application.name=minigame-platform

server.port=${PORT:8080}

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/minigame-platform
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
spring.security.oauth2.resourceserver.jwt.jws-algorithms=RS256
spring.security.oauth2.resourceserver.jwt.audiences=minigame-platform

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

springdoc.swagger-ui.path=/apidoc

logging.level.org.springframework.data.repository.config.RepositoryConfigurationDelegate=warn
logging.level.org.apache.catalina.core=warn
logging.level.org.hibernate.orm=warn
logging.level.com.zaxxer.hikari=warn
logging.level.org.springdoc.core.events=error
logging.level.org.springframework.data.jpa.repository.query.QueryEnhancerFactories=warn
logging.level.org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean=warn
logging.level.org.springframework.orm.jpa.persistenceunit.SpringPersistenceUnitInfo=warn
logging.level.org.springframework.boot.web.context.servlet.WebApplicationContextInitializer=warn
logging.level.org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler=warn
logging.level.org.springframework.web.SimpLogging=warn
